### ISSUE TITLE
Package is not compatible with ARM64

### ISSUE THREAD

**Issue by agoldis** [getsentry/profiling-node#107]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### SDK Version

0.2.2

### What environment is your node script running in?

FROM arm64v8/node:18-buster-slim as build

### How is your code deployed and bundled?

arm64 docker image

### Steps to Reproduce

```sh
docker run -it arm64v8/node:18-buster-slim sh
mkdir example 
cd example
npm init -y
npm i @sentry/profiling-node
```

### Expected Result

Expecting the package to be installed on arm64 docker containers

### Actual Result

[4/4] Building fresh packages...
130 | error /tmp/node_modules/@sentry/profiling-node: Command failed.
131 | Exit code: 1
132 | Command: node scripts/check-build.js
133 | Arguments:
134 | Directory: /tmp/node_modules/@sentry/profiling-node
135 | Output:
136 | @sentry/profiling-node: Precompiled binary found, attempting to load...
137 | @sentry/profiling-node: Compiling from source...
138 | gyp info it worked if it ends with ok
139 | gyp info using node-gyp@9.3.1
140 | gyp info using node@18.14.2 \| linux \| arm64
141 | gyp ERR! find Python
142 | gyp ERR! find Python Python is not set from command line or npm configuration
143 | gyp ERR! find Python Python is not set from environment variable PYTHON
144 | gyp ERR! find Python checking if "python3" can be used
145 | gyp ERR! find Python - "python3" is not in PATH or produced an error
146 | gyp ERR! find Python checking if "python" can be used
147 | gyp ERR! find Python - "python" is not in PATH or produced an error
148 | gyp ERR! find Python
149 | gyp ERR! find Python **********************************************************
150 | gyp ERR! find Python You need to install the latest version of Python.
151 | gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
152 | gyp ERR! find Python you can try one of the following options:
153 | gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
154 | gyp ERR! find Python   (accepted by both node-gyp and npm)
155 | gyp ERR! find Python - Set the environment variable PYTHON
156 | gyp ERR! find Python - Set the npm configuration variable python:
157 | gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
158 | gyp ERR! find Python For more information consult the documentation at:
159 | gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
160 | gyp ERR! find Python **********************************************************
161 | gyp ERR! find Python
162 | gyp ERR! configure error
163 | gyp ERR! stack Error: Could not find any Python installation to use
164 | gyp ERR! stack     at PythonFinder.fail (/tmp/node_modules/node-gyp/lib/find-python.js:330:47)
165 | gyp ERR! stack     at PythonFinder.runChecks (/tmp/node_modules/node-gyp/lib/find-python.js:159:21)
166 | gyp ERR! stack     at PythonFinder.<anonymous> (/tmp/node_modules/node-gyp/lib/find-python.js:202:16)
167 | gyp ERR! stack     at PythonFinder.execFileCallback (/tmp/node_modules/node-gyp/lib/find-python.js:294:16)
168 | gyp ERR! stack     at exithandler (node:child_process:427:5)
169 | gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
170 | gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
171 | gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
172 | gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
173 | gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
174 | gyp ERR! System Linux 4.14.248-189.473.amzn2.aarch64
175 | gyp ERR! command "/usr/local/bin/node" "/tmp/node_modules/@sentry/profiling-node/node_modules/.bin/node-gyp" "configure"
176 | gyp ERR! cwd /tmp/node_modules/@sentry/profiling-node
177 | gyp ERR! node -v v18.14.2
178 | gyp ERR! node-gyp -v v9.3.1
179 | gyp ERR! not ok
180 | npm notice
181 | npm notice New patch version of npm available! 9.5.0 -> 9.5.1
182 | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.5.1>
183 | npm notice Run `npm install -g npm@9.5.1` to update!
184 | npm notice
185 | @sentry/profiling-node: Failed to build from source, please report this a bug at https://github.com/getsentry/profiling-node/issues/new?assignees=&labels=Type%3A+Bug&template=bug.yml
186 | /tmp/node_modules/@sentry/profiling-node/scripts/check-build.js:51
187 | throw e;
188 | ^
189 |  
190 | Error: /tmp/node_modules/@sentry/profiling-node/binaries/sentry_cpu_profiler-v108-linux-arm64-glibc.node: cannot open shared object file: No such file or directory
191 | at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
192 | at Module.load (node:internal/modules/cjs/loader:1117:32)
193 | at Module._load (node:internal/modules/cjs/loader:958:12)
194 | at Module.require (node:internal/modules/cjs/loader:1141:19)
195 | at require (node:internal/modules/cjs/helpers:110:18)
196 | at Object.<anonymous> (/tmp/node_modules/@sentry/profiling-node/scripts/check-build.js:24:3)
197 | at Module._compile (node:internal/modules/cjs/loader:1254:14)
198 | at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
199 | at Module.load (node:internal/modules/cjs/loader:1117:32)
200 | at Module._load (node:internal/modules/cjs/loader:958:12) {
201 | code: 'ERR_DLOPEN_FAILED'
202 | }
203

<br class="Apple-interchange-newline">

**Comment by JonasBa** [comment]
@agoldis we do not provide a precompiled bindings for arm64v8, so the package attempts to compile from source and fails as it cannot find python3. 
>163 | gyp ERR! stack Error: Could not find any Python installation to use

You will need to install python3 before running npm install (this is a standard requirement for any package that uses native modules) and I suspect you will might also need to install `make` and `g++`. After you install the build dependencies, the package should build from source and npm install should no longer fail.

Let me know how it goes, we'll be happy to help you

**Comment by JonasBa** [comment]
@agoldis any updates? 

If you have not yet managed to resolve this, mind sending us the output of running `npm install --verbose --foreground-scripts @sentry/profiling-node` in an empty directory?

**Comment by agoldis** [comment]
Nope, I didn't want to bloat the Docker image. Ended up switching to datadog 😝

**Comment by JonasBa** [comment]
@agoldis oh dang, that's not nice to hear, but glad you got it working at least!

**Comment by JonasBa** [comment]
@agoldis I will close the issue and see if we can provide prebuilt images for arm64v8 in the future
