### ISSUE TITLE
@sentry/core should be listed as a dependency 

### ISSUE THREAD

**Issue by vidhu** [getsentry/profiling-node#124]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### SDK Version

0.3.0

### What environment is your node script running in?

- node v16.17.0
- yarn 2 (berry)

### How is your code deployed and bundled?

-

### Steps to Reproduce

Assuming you're using yarn 2

`$ yarn add @sentry/profiling-node`

```ts
// index.js
// typical setup
import Sentry from '@sentry/node';
import { ProfilingIntegration } from '@sentry/profiling-node';
import '@sentry/tracing';
...

Sentry.init({
  ...
  integrations: [new ProfilingIntegration()],
  ...
});
```

### Expected Result

Application should start

### Actual Result

Application fails to start. Yarn raises an error because `@sentry/core` is not a declared dependency even though it is directly used in this package [eg here](https://github.com/getsentry/profiling-node/blob/main/src/hubextensions.ts#L8)

## Log
```
yarn start

/code/.pnp.cjs:75642
      Error.captureStackTrace(firstError);
            ^
Error: @sentry/profiling-node tried to access @sentry/core, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @sentry/core
Required by: @sentry/profiling-node@npm:0.3.0 (via /code/.yarn/unplugged/@sentry-profiling-node-npm-0.3.0-25372e22a8/node_modules/@sentry/profiling-node/lib/)

Require stack:
- /code/.yarn/unplugged/@sentry-profiling-node-npm-0.3.0-25372e22a8/node_modules/@sentry/profiling-node/lib/hubextensions.js
- /code/.yarn/unplugged/@sentry-profiling-node-npm-0.3.0-25372e22a8/node_modules/@sentry/profiling-node/lib/integration.js
- /code/.yarn/unplugged/@sentry-profiling-node-npm-0.3.0-25372e22a8/node_modules/@sentry/profiling-node/lib/index.js
- /code/src/sentry.ts
- /code/src/index.ts
    at Function.require$$0.Module._resolveFilename (/code/.pnp.cjs:75642:13)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/code/.yarn/cache/@cspotcode-source-map-support-npm-0.7.0-456c3ea2ce-9faddda775.zip/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.require$$0.Module._load (/code/.pnp.cjs:75492:42)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/code/.yarn/unplugged/@sentry-profiling-node-npm-0.3.0-25372e22a8/node_modules/@sentry/profiling-node/lib/hubextensions.js:8:16)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at require$$0.Module._extensions..js (/code/.pnp.cjs:75686:33)
    at Object.require.extensions.<computed> [as .js] (/code/.yarn/__virtual__/ts-node-virtual-50ad41090e/0/cache/ts-node-npm-10.7.0-ef39b1d45e-2a379e43f7.zip/node_modules/ts-node/src/index.ts:1445:43)
```

**Comment by vidhu** [comment]
I've created a PR which adds `@sentry/core:^7.44.0` as a dependency. Not 100% sure if this was left out intentionally but incase it wasn't, let me know if this is good!

**Comment by JonasBa** [comment]
@vidhu 🤔 must have probably been a peer dep that was loaded by other packages. Approved your PR and merging it, thanks for the contribution!
