### ISSUE TITLE
Install does not work w/o setting gcc flags 

### ISSUE THREAD

**Issue by vegardok** [getsentry/profiling-node#147]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### SDK Version

0.3.0

### What environment is your node script running in?

Apple M2 Pro, OSX Version 13.3.1 (a) (22E772610a)

```gcc -v
gcc -v
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
node -v
v18.16.0
```
```
package.json
{
  "name": "sentry-debug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@sentry/profiling-node": "^0.3.0"
  }
}
```

### How is your code deployed and bundled?

n/a

### Steps to Reproduce

`npm install` 

### Expected Result

```
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

added 109 packages, and audited 110 packages in 2s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

Running `CXXFLAGS="--std=c++14"  npm install` fixes the issue

### Actual Result

```
0 verbose cli /Users/vegardok/.nvm/versions/node/v18.16.0/bin/node /Users/vegardok/.nvm/versions/node/v18.16.0/bin/npm
1 info using npm@9.5.1
2 info using node@v18.16.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/vegardok/.nvm/versions/node/v18.16.0/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/vegardok/tmp/sentry-debug/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/Users/vegardok/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/Users/vegardok/.nvm/versions/node/v18.16.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 3ms
17 timing npm:load:configload Completed in 3ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install
21 verbose argv "install"
22 timing npm:load:setTitle Completed in 5ms
23 timing config:load:flatten Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/Users/vegardok/.npm/_logs/2023-05-10T07_27_43_215Z-
26 verbose logfile /Users/vegardok/.npm/_logs/2023-05-10T07_27_43_215Z-debug-0.log
27 timing npm:load:logFile Completed in 3ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 12ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 27ms
35 timing idealTree:userRequests Completed in 0ms
36 silly idealTree buildDeps
37 timing idealTree:#root Completed in 0ms
38 timing idealTree:buildDeps Completed in 0ms
39 timing idealTree:fixDepFlags Completed in 0ms
40 timing idealTree Completed in 29ms
41 timing reify:loadTrees Completed in 30ms
42 timing reify:diffTrees Completed in 1ms
43 silly reify moves {}
44 timing reify:retireShallow Completed in 1ms
45 timing reify:createSparse Completed in 5ms
46 timing reify:loadBundles Completed in 0ms
47 silly audit bulk request {
47 silly audit   '@gar/promisify': [ '1.1.3' ],
47 silly audit   '@npmcli/fs': [ '2.1.2' ],
47 silly audit   '@npmcli/move-file': [ '2.0.1' ],
47 silly audit   '@sentry-internal/tracing': [ '7.51.2' ],
47 silly audit   '@sentry/core': [ '7.51.2' ],
47 silly audit   '@sentry/hub': [ '7.51.2' ],
47 silly audit   '@sentry/node': [ '7.51.2' ],
47 silly audit   '@sentry/profiling-node': [ '0.3.0' ],
47 silly audit   '@sentry/tracing': [ '7.51.2' ],
47 silly audit   '@sentry/types': [ '7.51.2' ],
47 silly audit   '@sentry/utils': [ '7.51.2' ],
47 silly audit   '@tootallnate/once': [ '2.0.0' ],
47 silly audit   abbrev: [ '1.1.1' ],
47 silly audit   'agent-base': [ '6.0.2' ],
47 silly audit   agentkeepalive: [ '4.3.0' ],
47 silly audit   'aggregate-error': [ '3.1.0' ],
47 silly audit   'ansi-regex': [ '5.0.1' ],
47 silly audit   aproba: [ '2.0.0' ],
47 silly audit   'are-we-there-yet': [ '3.0.1' ],
47 silly audit   'balanced-match': [ '1.0.2' ],
47 silly audit   'brace-expansion': [ '1.1.11', '2.0.1' ],
47 silly audit   cacache: [ '16.1.3' ],
47 silly audit   glob: [ '8.1.0', '7.2.3' ],
47 silly audit   minimatch: [ '5.1.6', '3.1.2' ],
47 silly audit   chownr: [ '2.0.0' ],
47 silly audit   'clean-stack': [ '2.2.0' ],
47 silly audit   'color-support': [ '1.1.3' ],
47 silly audit   'concat-map': [ '0.0.1' ],
47 silly audit   'console-control-strings': [ '1.1.0' ],
47 silly audit   cookie: [ '0.4.2' ],
47 silly audit   debug: [ '4.3.4' ],
47 silly audit   delegates: [ '1.0.0' ],
47 silly audit   depd: [ '2.0.0' ],
47 silly audit   'detect-libc': [ '2.0.1' ],
47 silly audit   'emoji-regex': [ '8.0.0' ],
47 silly audit   encoding: [ '0.1.13' ],
47 silly audit   'env-paths': [ '2.2.1' ],
47 silly audit   'err-code': [ '2.0.3' ],
47 silly audit   'fs-minipass': [ '2.1.0' ],
47 silly audit   'fs.realpath': [ '1.0.0' ],
47 silly audit   gauge: [ '4.0.4' ],
47 silly audit   'graceful-fs': [ '4.2.11' ],
47 silly audit   'has-unicode': [ '2.0.1' ],
47 silly audit   'http-cache-semantics': [ '4.1.1' ],
47 silly audit   'http-proxy-agent': [ '5.0.0' ],
47 silly audit   'https-proxy-agent': [ '5.0.1' ],
47 silly audit   'humanize-ms': [ '1.2.1' ],
47 silly audit   'iconv-lite': [ '0.6.3' ],
47 silly audit   imurmurhash: [ '0.1.4' ],
47 silly audit   'indent-string': [ '4.0.0' ],
47 silly audit   'infer-owner': [ '1.0.4' ],
47 silly audit   inflight: [ '1.0.6' ],
47 silly audit   inherits: [ '2.0.4' ],
47 silly audit   ip: [ '2.0.0' ],
47 silly audit   'is-fullwidth-code-point': [ '3.0.0' ],
47 silly audit   'is-lambda': [ '1.0.1' ],
47 silly audit   isexe: [ '2.0.0' ],
47 silly audit   lru_map: [ '0.3.3' ],
47 silly audit   'lru-cache': [ '7.18.3', '6.0.0' ],
47 silly audit   'make-fetch-happen': [ '10.2.1' ],
47 silly audit   minipass: [ '3.3.6', '5.0.0' ],
47 silly audit   'minipass-collect': [ '1.0.2' ],
47 silly audit   'minipass-fetch': [ '2.1.2' ],
47 silly audit   'minipass-flush': [ '1.0.5' ],
47 silly audit   'minipass-pipeline': [ '1.2.4' ],
47 silly audit   'minipass-sized': [ '1.0.3' ],
47 silly audit   minizlib: [ '2.1.2' ],
47 silly audit   mkdirp: [ '1.0.4' ],
47 silly audit   ms: [ '2.1.2' ],
47 silly audit   nan: [ '2.17.0' ],
47 silly audit   negotiator: [ '0.6.3' ],
47 silly audit   'node-abi': [ '3.40.0' ],
47 silly audit   'node-gyp': [ '9.3.1' ],
47 silly audit   nopt: [ '6.0.0' ],
47 silly audit   npmlog: [ '6.0.2' ],
47 silly audit   once: [ '1.4.0' ],
47 silly audit   'p-map': [ '4.0.0' ],
47 silly audit   'path-is-absolute': [ '1.0.1' ],
47 silly audit   'promise-inflight': [ '1.0.1' ],
47 silly audit   'promise-retry': [ '2.0.1' ],
47 silly audit   'readable-stream': [ '3.6.2' ],
47 silly audit   retry: [ '0.12.0' ],
47 silly audit   rimraf: [ '3.0.2' ],
47 silly audit   'safe-buffer': [ '5.2.1' ],
47 silly audit   'safer-buffer': [ '2.1.2' ],
47 silly audit   semver: [ '7.5.0' ],
47 silly audit   'set-blocking': [ '2.0.0' ],
47 silly audit   'signal-exit': [ '3.0.7' ],
47 silly audit   'smart-buffer': [ '4.2.0' ],
47 silly audit   socks: [ '2.7.1' ],
47 silly audit   'socks-proxy-agent': [ '7.0.0' ],
47 silly audit   ssri: [ '9.0.1' ],
47 silly audit   string_decoder: [ '1.3.0' ],
47 silly audit   'string-width': [ '4.2.3' ],
47 silly audit   'strip-ansi': [ '6.0.1' ],
47 silly audit   tar: [ '6.1.14' ],
47 silly audit   tslib: [ '1.14.1' ],
47 silly audit   'unique-filename': [ '2.0.1' ],
47 silly audit   'unique-slug': [ '3.0.0' ],
47 silly audit   'util-deprecate': [ '1.0.2' ],
47 silly audit   which: [ '2.0.2' ],
47 silly audit   'wide-align': [ '1.1.5' ],
47 silly audit   wrappy: [ '1.0.2' ],
47 silly audit   yallist: [ '4.0.0' ]
47 silly audit }
48 timing reifyNode:node_modules/wrappy Completed in 111ms
49 timing reifyNode:node_modules/wide-align Completed in 111ms
50 timing reifyNode:node_modules/promise-inflight Completed in 111ms
51 timing reifyNode:node_modules/once Completed in 112ms
52 timing reifyNode:node_modules/path-is-absolute Completed in 112ms
53 timing reifyNode:node_modules/ms Completed in 112ms
54 timing reifyNode:node_modules/minipass-flush Completed in 112ms
55 timing reifyNode:node_modules/minipass-pipeline Completed in 112ms
56 timing reifyNode:node_modules/minipass-collect Completed in 112ms
57 timing reifyNode:node_modules/infer-owner Completed in 112ms
58 timing reifyNode:node_modules/inflight Completed in 112ms
59 timing reifyNode:node_modules/ip Completed in 112ms
60 timing reifyNode:node_modules/imurmurhash Completed in 112ms
61 timing reifyNode:node_modules/has-unicode Completed in 112ms
62 timing reifyNode:node_modules/chownr Completed in 113ms
63 timing reifyNode:node_modules/brace-expansion Completed in 113ms
64 timing reifyNode:node_modules/abbrev Completed in 113ms
65 timing reifyNode:node_modules/@gar/promisify Completed in 113ms
66 timing reifyNode:node_modules/unique-slug Completed in 114ms
67 timing reifyNode:node_modules/unique-filename Completed in 114ms
68 timing reifyNode:node_modules/string-width Completed in 115ms
69 timing reifyNode:node_modules/strip-ansi Completed in 115ms
70 timing reifyNode:node_modules/set-blocking Completed in 115ms
71 timing reifyNode:node_modules/signal-exit Completed in 115ms
72 timing reifyNode:node_modules/p-map Completed in 115ms
73 timing reifyNode:node_modules/is-fullwidth-code-point Completed in 114ms
74 timing reifyNode:node_modules/inherits Completed in 115ms
75 timing reifyNode:node_modules/indent-string Completed in 115ms
76 timing reifyNode:node_modules/humanize-ms Completed in 115ms
77 timing reifyNode:node_modules/fs-minipass Completed in 115ms
78 timing reifyNode:node_modules/env-paths Completed in 115ms
79 timing reifyNode:node_modules/console-control-strings Completed in 115ms
80 timing reifyNode:node_modules/clean-stack Completed in 115ms
81 timing reifyNode:node_modules/ansi-regex Completed in 115ms
82 timing reifyNode:node_modules/aproba Completed in 115ms
83 timing reifyNode:node_modules/aggregate-error Completed in 115ms
84 timing reifyNode:node_modules/semver/node_modules/lru-cache Completed in 117ms
85 warn deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
86 timing reifyNode:node_modules/@npmcli/move-file Completed in 116ms
87 timing reifyNode:node_modules/yallist Completed in 117ms
88 timing reifyNode:node_modules/util-deprecate Completed in 117ms
89 timing reifyNode:node_modules/string_decoder Completed in 117ms
90 timing reifyNode:node_modules/npmlog Completed in 117ms
91 timing reifyNode:node_modules/fs.realpath Completed in 117ms
92 timing reifyNode:node_modules/color-support Completed in 117ms
93 timing reifyNode:node_modules/cookie Completed in 117ms
94 timing reifyNode:node_modules/balanced-match Completed in 117ms
95 timing reifyNode:node_modules/which Completed in 119ms
96 timing reifyNode:node_modules/cacache/node_modules/brace-expansion Completed in 118ms
97 timing reifyNode:node_modules/minizlib Completed in 119ms
98 timing reifyNode:node_modules/minimatch Completed in 119ms
99 timing reifyNode:node_modules/is-lambda Completed in 118ms
100 timing reifyNode:node_modules/http-cache-semantics Completed in 119ms
101 timing reifyNode:node_modules/graceful-fs Completed in 119ms
102 timing reifyNode:node_modules/socks-proxy-agent Completed in 120ms
103 timing reifyNode:node_modules/ssri Completed in 121ms
104 timing reifyNode:node_modules/safe-buffer Completed in 121ms
105 timing reifyNode:node_modules/rimraf Completed in 121ms
106 timing reifyNode:node_modules/cacache/node_modules/minimatch Completed in 121ms
107 timing reifyNode:node_modules/nopt Completed in 122ms
108 timing reifyNode:node_modules/http-proxy-agent Completed in 121ms
109 timing reifyNode:node_modules/detect-libc Completed in 121ms
110 timing reifyNode:node_modules/encoding Completed in 122ms
111 timing reifyNode:node_modules/delegates Completed in 122ms
112 timing reifyNode:node_modules/concat-map Completed in 122ms
113 timing reifyNode:node_modules/debug Completed in 122ms
114 timing reifyNode:node_modules/safer-buffer Completed in 123ms
115 timing reifyNode:node_modules/isexe Completed in 122ms
116 timing reifyNode:node_modules/minipass Completed in 124ms
117 timing reifyNode:node_modules/depd Completed in 123ms
118 timing reifyNode:node_modules/are-we-there-yet Completed in 123ms
119 timing reifyNode:node_modules/promise-retry Completed in 124ms
120 timing reifyNode:node_modules/err-code Completed in 124ms
121 timing reifyNode:node_modules/glob Completed in 124ms
122 timing reifyNode:node_modules/cacache/node_modules/glob Completed in 124ms
123 timing reifyNode:node_modules/emoji-regex Completed in 125ms
124 timing reifyNode:node_modules/tar/node_modules/minipass Completed in 126ms
125 timing reifyNode:node_modules/negotiator Completed in 126ms
126 timing reifyNode:node_modules/@tootallnate/once Completed in 125ms
127 timing reifyNode:node_modules/mkdirp Completed in 127ms
128 timing reifyNode:node_modules/lru-cache Completed in 127ms
129 timing reifyNode:node_modules/@sentry/hub Completed in 126ms
130 timing reifyNode:node_modules/tslib Completed in 128ms
131 timing reifyNode:node_modules/minipass-sized Completed in 128ms
132 timing reifyNode:node_modules/https-proxy-agent Completed in 127ms
133 timing reifyNode:node_modules/lru_map Completed in 127ms
134 timing reifyNode:node_modules/agentkeepalive Completed in 127ms
135 timing reifyNode:node_modules/agent-base Completed in 128ms
136 timing reifyNode:node_modules/minipass-fetch Completed in 129ms
137 timing reifyNode:node_modules/@sentry/tracing Completed in 129ms
138 timing reifyNode:node_modules/retry Completed in 131ms
139 timing reifyNode:node_modules/node-abi Completed in 132ms
140 timing reifyNode:node_modules/make-fetch-happen Completed in 133ms
141 timing reifyNode:node_modules/gauge Completed in 132ms
142 timing reifyNode:node_modules/smart-buffer Completed in 134ms
143 timing reifyNode:node_modules/cacache Completed in 133ms
144 timing reifyNode:node_modules/@npmcli/fs Completed in 135ms
145 timing reifyNode:node_modules/readable-stream Completed in 138ms
146 timing reifyNode:node_modules/tar Completed in 140ms
147 timing reifyNode:node_modules/semver Completed in 143ms
148 timing reifyNode:node_modules/socks Completed in 147ms
149 timing reifyNode:node_modules/iconv-lite Completed in 146ms
150 timing reifyNode:node_modules/nan Completed in 151ms
151 timing reifyNode:node_modules/@sentry/types Completed in 153ms
152 timing reifyNode:node_modules/@sentry/profiling-node Completed in 155ms
153 timing reifyNode:node_modules/@sentry/core Completed in 177ms
154 timing reifyNode:node_modules/@sentry/node Completed in 182ms
155 timing reifyNode:node_modules/@sentry-internal/tracing Completed in 182ms
156 timing reifyNode:node_modules/node-gyp Completed in 184ms
157 timing reifyNode:node_modules/@sentry/utils Completed in 186ms
158 timing reify:unpack Completed in 187ms
159 timing reify:unretire Completed in 1ms
160 timing build:queue Completed in 1ms
161 timing build:link:node_modules/color-support Completed in 2ms
162 timing build:link:node_modules/nopt Completed in 1ms
163 timing build:link:node_modules/mkdirp Completed in 1ms
164 timing build:link:node_modules/node-gyp Completed in 1ms
165 timing build:link:node_modules/rimraf Completed in 1ms
166 timing build:link:node_modules/semver Completed in 1ms
167 timing build:link:node_modules/which Completed in 1ms
168 timing build:link Completed in 2ms
169 info run @sentry/profiling-node@0.3.0 install node_modules/@sentry/profiling-node node scripts/empty.js
170 info run @sentry/profiling-node@0.3.0 install { code: 0, signal: null }
171 timing build:run:install:node_modules/@sentry/profiling-node Completed in 30ms
172 timing build:run:install Completed in 30ms
173 info run @sentry/profiling-node@0.3.0 postinstall node_modules/@sentry/profiling-node node scripts/check-build.js
174 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 352ms
175 timing auditReport:getReport Completed in 353ms
176 silly audit report {}
177 timing auditReport:init Completed in 0ms
178 timing reify:audit Completed in 353ms
179 info run @sentry/profiling-node@0.3.0 postinstall { code: 1, signal: null }
180 timing reify:rollback:createSparse Completed in 98ms
181 timing reify:rollback:retireShallow Completed in 0ms
182 timing command:install Completed in 1552ms
183 verbose stack Error: command failed
183 verbose stack     at ChildProcess.<anonymous> (/Users/vegardok/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
183 verbose stack     at ChildProcess.emit (node:events:513:28)
183 verbose stack     at maybeClose (node:internal/child_process:1091:16)
183 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
184 verbose pkgid @sentry/profiling-node@0.3.0
185 verbose cwd /Users/vegardok/tmp/sentry-debug
186 verbose Darwin 22.4.0
187 verbose node v18.16.0
188 verbose npm  v9.5.1
189 error code 1
190 error path /Users/vegardok/tmp/sentry-debug/node_modules/@sentry/profiling-node
191 error command failed
192 error command sh -c node scripts/check-build.js
193 error @sentry/profiling-node: Precompiled binary found, attempting to load...
193 error @sentry/profiling-node: Compiling from source...
194 error gyp info it worked if it ends with ok
194 error gyp info using node-gyp@9.3.1
194 error gyp info using node@18.16.0 | darwin | arm64
194 error gyp info find Python using Python version 3.9.6 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
194 error gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
194 error gyp info spawn args [
194 error gyp info spawn args   '/Users/vegardok/tmp/sentry-debug/node_modules/node-gyp/gyp/gyp_main.py',
194 error gyp info spawn args   'binding.gyp',
194 error gyp info spawn args   '-f',
194 error gyp info spawn args   'make',
194 error gyp info spawn args   '-I',
194 error gyp info spawn args   '/Users/vegardok/tmp/sentry-debug/node_modules/@sentry/profiling-node/build/config.gypi',
194 error gyp info spawn args   '-I',
194 error gyp info spawn args   '/Users/vegardok/tmp/sentry-debug/node_modules/node-gyp/addon.gypi',
194 error gyp info spawn args   '-I',
194 error gyp info spawn args   '/Users/vegardok/Library/Caches/node-gyp/18.16.0/include/node/common.gypi',
194 error gyp info spawn args   '-Dlibrary=shared_library',
194 error gyp info spawn args   '-Dvisibility=default',
194 error gyp info spawn args   '-Dnode_root_dir=/Users/vegardok/Library/Caches/node-gyp/18.16.0',
194 error gyp info spawn args   '-Dnode_gyp_dir=/Users/vegardok/tmp/sentry-debug/node_modules/node-gyp',
194 error gyp info spawn args   '-Dnode_lib_file=/Users/vegardok/Library/Caches/node-gyp/18.16.0/<(target_arch)/node.lib',
194 error gyp info spawn args   '-Dmodule_root_dir=/Users/vegardok/tmp/sentry-debug/node_modules/@sentry/profiling-node',
194 error gyp info spawn args   '-Dnode_engine=v8',
194 error gyp info spawn args   '--depth=.',
194 error gyp info spawn args   '--no-parallel',
194 error gyp info spawn args   '--generator-output',
194 error gyp info spawn args   'build',
194 error gyp info spawn args   '-Goutput_dir=.'
194 error gyp info spawn args ]
194 error gyp info ok 
194 error gyp info it worked if it ends with ok
194 error gyp info using node-gyp@9.3.1
194 error gyp info using node@18.16.0 | darwin | arm64
194 error gyp info spawn make
194 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
194 error In file included from ../bindings/cpu_profiler.cc:4:
194 error In file included from ../../../nan/nan.h:60:
194 error In file included from /Users/vegardok/Library/Caches/node-gyp/18.16.0/include/node/node.h:73:
194 error In file included from /Users/vegardok/Library/Caches/node-gyp/18.16.0/include/node/v8.h:24:
194 error In file included from /Users/vegardok/Library/Caches/node-gyp/18.16.0/include/node/v8-array-buffer.h:12:
194 error In file included from /Users/vegardok/Library/Caches/node-gyp/18.16.0/include/node/v8-local-handle.h:12:
194 error /Users/vegardok/Library/Caches/node-gyp/18.16.0/include/node/v8-internal.h:646:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
194 error             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
194 error                                 ~~~~~^~~~~~~~~~~
194 error                                      remove_cv
194 error /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/remove_cv.h:22:50: note: 'remove_cv' declared here
194 error template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
194 error                                                  ^
194 error 1 error generated.
194 error make: *** [Release/obj.target/sentry_cpu_profiler/bindings/cpu_profiler.o] Error 1
194 error gyp ERR! build error 
194 error gyp ERR! stack Error: `make` failed with exit code: 2
194 error gyp ERR! stack     at ChildProcess.onExit (/Users/vegardok/tmp/sentry-debug/node_modules/node-gyp/lib/build.js:203:23)
194 error gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
194 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
194 error gyp ERR! System Darwin 22.4.0
194 error gyp ERR! command "/Users/vegardok/.nvm/versions/node/v18.16.0/bin/node" "/Users/vegardok/tmp/sentry-debug/node_modules/.bin/node-gyp" "build"
194 error gyp ERR! cwd /Users/vegardok/tmp/sentry-debug/node_modules/@sentry/profiling-node
194 error gyp ERR! node -v v18.16.0
194 error gyp ERR! node-gyp -v v9.3.1
194 error gyp ERR! not ok 
194 error @sentry/profiling-node: Failed to build from source, please report this a bug at https://github.com/getsentry/profiling-node/issues/new?assignees=&labels=Type%3A+Bug&template=bug.yml
194 error /Users/vegardok/tmp/sentry-debug/node_modules/@sentry/profiling-node/scripts/check-build.js:51
194 error   throw e;
194 error   ^
194 error
194 error Error: Cannot find module '/Users/vegardok/tmp/sentry-debug/node_modules/@sentry/profiling-node/binaries/sentry_cpu_profiler-v108-darwin-arm64.node'
194 error Require stack:
194 error - /Users/vegardok/tmp/sentry-debug/node_modules/@sentry/profiling-node/scripts/check-build.js
194 error     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
194 error     at Module._load (node:internal/modules/cjs/loader:920:27)
194 error     at Module.require (node:internal/modules/cjs/loader:1141:19)
194 error     at require (node:internal/modules/cjs/helpers:110:18)
194 error     at Object.<anonymous> (/Users/vegardok/tmp/sentry-debug/node_modules/@sentry/profiling-node/scripts/check-build.js:24:3)
194 error     at Module._compile (node:internal/modules/cjs/loader:1254:14)
194 error     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
194 error     at Module.load (node:internal/modules/cjs/loader:1117:32)
194 error     at Module._load (node:internal/modules/cjs/loader:958:12)
194 error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
194 error   code: 'MODULE_NOT_FOUND',
194 error   requireStack: [
194 error     '/Users/vegardok/tmp/sentry-debug/node_modules/@sentry/profiling-node/scripts/check-build.js'
194 error   ]
194 error }
194 error
194 error Node.js v18.16.0
195 verbose exit 1
196 timing npm Completed in 2213ms
197 verbose unfinished npm timer reify 1683703663232
198 verbose unfinished npm timer reify:build 1683703663463
199 verbose unfinished npm timer build 1683703663463
200 verbose unfinished npm timer build:deps 1683703663463
201 verbose unfinished npm timer build:run:postinstall 1683703663496
202 verbose unfinished npm timer build:run:postinstall:node_modules/@sentry/profiling-node 1683703663496
203 verbose code 1
204 error A complete log of this run can be found in:
204 error     /Users/vegardok/.npm/_logs/2023-05-10T07_27_43_215Z-debug-0.log
```

**Comment by vegardok** [comment]
This was a user error on my side, I set up a new machine with some old dotfiles that had this in it 🤦 `export CPPFLAGS="-std=c++11"`

**Comment by JonasBa** [comment]
Glad you got it working!
