### ISSUE TITLE
v1.0.0: `Error: Dynamic require of "child_process" is not supported`

### ISSUE THREAD

**Issue by ldiqual** [getsentry/profiling-node#160]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### SDK Version

1.0.0

### What environment is your node script running in?

MacOS with node v18. Script runs within ts-node.

### How is your code deployed and bundled?

No bundling, this is server-side and transpiled by ts-node

### Steps to Reproduce

Upgrade to @sentry/profiling-node v1, enable profiling integration

### Expected Result

Script starts

### Actual Result

Script crashes with the following error:

```
Error: Dynamic require of "child_process" is not supported
    at file://path/to/node_modules/@sentry/profiling-node/lib/index.mjs:12:9
    at node_modules/detect-libc/lib/detect-libc.js (file://path/to/node_modules/@sentry/profiling-node/lib/index.mjs:9512:24)
    at __require2 (file://path/to/node_modules/@sentry/profiling-node/lib/index.mjs:15:50)
    at file://path/to/node_modules/@sentry/profiling-node/lib/index.mjs:16572:34
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by JonasBa** [comment]
@ldiqual I just added the require polyfill and release 1.0.1, do you mind giving it a try and testing it?

**Comment by thenbe** [comment]
@JonasBa I was getting the same error as OP in two different projects (a node server and a sveltekit app). After updating to `1.0.1`, the node server works OK. But the sveltekit app has this error:

```
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".node" for /home/nbe/projects/project/node_modules/.pnpm/@sentry+profiling-node@1.0.1/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-x64-glibc-108.node
    at new NodeError (node:internal/errors:399:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v18.16.0
```

**Comment by JonasBa** [comment]
Ugh, seems esm cannot import .node same way as require can... I'll make sure we just use require in both builds, will publish 1.0.2 soon

**Comment by thenbe** [comment]
`1.0.2` was OK. But getting the same error mentioned [here](https://github.com/getsentry/profiling-node/issues/160#issuecomment-1583516459) in `1.0.3`.

```
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".node" for /home/nbe/projects/project/node_modules/.pnpm/@sentry+profiling-node@1.0.3/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-x64-glibc-108.node
    at new NodeError (node:internal/errors:399:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v18.16.0
```

**Comment by JonasBa** [comment]
@thenbe What happens if you import {ProfilingIntegration} from "@sentry/profiling-node/lib/index.js" ?

In all honesty, the entire ESM<->CJS has been such a pain to work with that I am considering entirely removing ESM support.
