### ISSUE TITLE
1.0.7 ./sentry_cpu_profiler-darwin-arm64-115.node not found

### ISSUE THREAD

**Issue by andylacko** [getsentry/profiling-node#171]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### SDK Version

1.0.7

### What environment is your node script running in?

20.3.1
pnpm

### How is your code deployed and bundled?

webpack

### Steps to Reproduce

try to run project

### Expected Result

work

### Actual Result

Error: Cannot find module './sentry_cpu_profiler-darwin-arm64-115.node'
Require stack:
- /Users/andy/Developer/intellcre/node_modules/.pnpm/@sentry+profiling-node@1.0.7/node_modules/@sentry/profiling-node/lib/index.js
- /Users/andy/Developer/intellcre/services/api/dist/services/api/src/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1072:15)
    at Function.Module._load (node:internal/modules/cjs/loader:925:27)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at /Users/andy/Developer/intellcre/node_modules/.pnpm/@sentry+profiling-node@1.0.7/node_modules/@sentry/profiling-node/lib/index.js:16691:57
    at importCppBindingsModule (/Users/andy/Developer/intellcre/node_modules/.pnpm/@sentry+profiling-node@1.0.7/node_modules/@sentry/profiling-node/lib/index.js:16691:14)
    at /Users/andy/Developer/intellcre/node_modules/.pnpm/@sentry+profiling-node@1.0.7/node_modules/@sentry/profiling-node/lib/index.js:16717:32
^C/Users/andy/Developer/intellcre/services/api:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  api@0.0.1 start:dev: `pnpm run assets:copy && nest start --watch`
Command failed with signal "SIGTERM"
 ELIFECYCLE  Command failed.

**Comment by whaagmans** [comment]
#173 fixed the issue.

**Comment by stephenhmarsh** [comment]
Yeah I get almost the same error in my Next.js project running `@sentry/profiling-node` `1.0.7` (latest published)

```
Error: Cannot find module './sentry_cpu_profiler-darwin-arm64-108.node'
Require stack:
- /Users/stephen/dev/met-js/web/node_modules/@sentry/profiling-node/lib/index.js
- /Users/stephen/dev/met-js/web/.next/server/pages/_document.js
- /Users/stephen/dev/met-js/web/node_modules/next/dist/server/require.js
- /Users/stephen/dev/met-js/web/node_modules/next/dist/server/load-components.js
- /Users/stephen/dev/met-js/web/node_modules/next/dist/build/utils.js
- /Users/stephen/dev/met-js/web/node_modules/next/dist/server/dev/static-paths-worker.js
- /Users/stephen/dev/met-js/web/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at /Users/stephen/dev/met-js/web/node_modules/next/dist/server/require-hook.js:189:36
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at /Users/stephen/dev/met-js/web/node_modules/@sentry/profiling-node/lib/index.js:16691:57
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async importCppBindingsModule (/Users/stephen/dev/met-js/web/node_modules/@sentry/profiling-node/lib/index.js:16691:14)
    at async /Users/stephen/dev/met-js/web/node_modules/@sentry/profiling-node/lib/index.js:16717:32
```

It looks like https://github.com/getsentry/profiling-node/pull/173 would fix this.  Running those commands separately and manually from the terminal resolved this.

**Comment by JonasBa** [comment]
We've released 1.0.8 and some folks internally at Sentry who had issues have said that they now seem to be resolved. Do you mind upgrading and letting me know if this still happens?

**Comment by Klaitos** [comment]
Error still persists `Cannot find module './sentry_cpu_profiler-darwin-arm64-115.node`  with node v18.16.0

**Comment by whaagmans** [comment]
> SENTRY_PROFILER_BINARY_PATH=./sentry_cpu_profiler-darwin-arm64-108.node

I don't have this token set. Where is yours located? It could be due to the token being set it overrides the default space it looks for the file.

**Comment by Klaitos** [comment]
The issue is here `https://github.com/getsentry/profiling-node/blob/ef598f4c7acbbcbe762a8ce6af04b92a0e82c371/src/cpu_profiler.ts#L2`, the `versions` variable returned by the import is `versions`, while my code is running on node 18.04. I guess this var is compiled at the build time, when you build and upload the package it is saved inside.

**Comment by whaagmans** [comment]
> The issue is here `https://github.com/getsentry/profiling-node/blob/main/src/cpu_profiler.ts#L2`, the `versions` variable returned by the import is `20.04`, while my code is running on node 18.04. I guess this var is read at the build time, when you build and upload the package it is saved inside.

Maybe I am missing something but based on the Node docs the `process.versions` has been in there since 0.2 with the last update in 9.0. [https://nodejs.org/docs/latest-v18.x/api/process.html#processversions](https://nodejs.org/docs/latest-v18.x/api/process.html#processversions) So maybe the problem is in another part. But still weird that adding the ENV solves it.

**Comment by Klaitos** [comment]
No I don't npm ignore scripts

**Comment by Klaitos** [comment]
Oh I found this is related to yarn, because when I start my server with node (and nodemon) this works !

**Comment by whaagmans** [comment]
Interesting since i use yarn 😅. But then again I am also on the latest node version so maybe there lies the crux.

**Comment by JonasBa** [comment]
Anyone on the latest version of the package still experiencing this problem?

**Comment by nicksrandall** [comment]
> Anyone on the latest version of the package still experiencing this problem?

Yes, I'm still seeing this issue with PNPM.

**Comment by whaagmans** [comment]
> > Anyone on the latest version of the package still experiencing this problem?
> 
> Yes, I'm still seeing this issue with PNPM.

Probably you've already tried this but as a novelty, have you've already tried:

1. Remove the node_modules directory and the lock file (pnpm-lock.yaml).
2. pnpm store prune
3. Run pnpm install again.
4. Check whether the package in question is at the correct version by using pnpm list [package-name].

**Comment by JonasBa** [comment]
@nicksrandall can you please run a clean install as @whaagmans suggested? I just attempted to install the package via pnpm, build and run and I could not reproduce your error.

**Comment by yash-coded** [comment]
This is still unusable in M1 macs. Did anyone find a workaround for this?

**Comment by JonasBa** [comment]
@yash-coded are you using pnpm as well?

**Comment by yash-coded** [comment]
Hey @JonasBa, I'm using `node v18.16.1 (npm v9.5.1)`

**Comment by JonasBa** [comment]
@yash-coded are you by any chance ignoring install scripts? What does `npm config get ignore-scripts` output? Can you bump the package to version 1.1.2?

**Comment by nicksrandall** [comment]
@JonasBa I did a clean install and realized that I think the issue is with my bundler and maybe not pnpm? I'm using remix (which is using esbuild) and the server fails to start when I'm using this package because node can't find the .node file

**Comment by yash-coded** [comment]
ignore-scripts is set to false and we're already on 1.1.2
![Screenshot 2023-07-28 at 7 51 29 AM](https://github.com/getsentry/profiling-node/assets/59040091/896c5739-a7fe-4d5b-8358-07e420cadad9)

**Comment by yash-coded** [comment]
![Screenshot 2023-07-28 at 7 46 23 AM](https://github.com/getsentry/profiling-node/assets/59040091/feb40a9a-7942-4e66-810a-e3f23a967006)
Getting this error when I run my server but i didn't get any errors during installation.

**Comment by yash-coded** [comment]
Sorry about that, i switched to node 16 just to try another version when I took the screenshot but I was getting the same error with node 18: `node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-darwin-arm64-108.node, 0x0001)`

**Comment by JonasBa** [comment]
@yash-coded I dont think your install script ran for some reason (or your node version was different at install time). Can you cd into @sentry/profiling-node and manually run `node scripts/check-build.mjs` and tell me what it outputs? This should detect the runtime error and trigger a rebuild from source.

**Comment by JonasBa** [comment]
Hmm, I think compiling from source might fail here and we may be swallowing error. If a binary is successfully compiled from source on your local machine then it should work (or at least the error would have been different)

do you mind running `npm run build:configure`,`npm run build:bindings` and `node scripts/copy-target.mjs` in this order from the profiling dir and seeing if any of these fail?

**Comment by yash-coded** [comment]
`npm run build:configure` didn't fail but got following responses from other two commands

```
❯ npm run build:bindings

> @sentry/profiling-node@1.1.2 build:bindings
> node-gyp build && node scripts/copy-target.mjs

gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@18.16.1 | darwin | arm64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make ✖ ERR  Missing Makefile / Bakefile 
make ℹ info Run "make init" to generate a Makefile.
gyp info ok 
Source file does not exist: /path/to/repo/node_modules/@sentry/profiling-node/build/Release/sentry_cpu_profiler.node
```

```
❯ node scripts/copy-target.mjs
Source file does not exist: /path/to/repo/node_modules/@sentry/profiling-node/build/Release/sentry_cpu_profiler.node
```

**Comment by JonasBa** [comment]
Quick search for that error finds https://github.com/nodejs/node-report/issues/102#issuecomment-495027006

Do you have a `make` package installed that is being confused by make from the build toolchain?

**Comment by mrmckeb** [comment]
I'm hitting this issue too.
```
Error: Cannot find module '[project-path]/node_modules/.pnpm/@sentry+profiling-node@1.1.2/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-darwin-arm64-110.node'
```

I see the following `sentry_cpu_profiler-darwin-arm64-*` modules installed.

<img width="297" alt="image" src="https://github.com/getsentry/profiling-node/assets/5043083/ee1df590-ef04-4e54-aca4-2676d2e8c2f2">

**Comment by JonasBa** [comment]
@mrmckeb mind running the steps that I described manually in and tell me if you see errors? https://github.com/getsentry/profiling-node/issues/171#issuecomment-1655845706

**Comment by JonasBa** [comment]
Closing due to inactivity. @mrmckeb please make sure you don't have a "make" package installed that is confusing the build toolchain. If you still have an issue, please run the commands I described in [#171](https://github.com/getsentry/profiling-node/issues/171#issuecomment-1655845706) and paste the output

**Comment by miteshkotak** [comment]
I am still facing this issue but haven't got a fixed yet, with M1 Macs

**Comment by JonasBa** [comment]
@nicksrandall mind opening a new issue with an example stacktrace? This issue has been polluted by a mix of a few different errors (and causes) and I would like to not add to it.

**Comment by theobouwman** [comment]
I am seeing the same error on Google Cloud Run:
```
Error: Cannot find module '/usr/src/app/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-x64-glibc-120.node'
```

I am using this template https://github.com/GoogleCloudPlatform/cloud-run-microservice-template-nodejs

**Comment by jamespsterling** [comment]
> I am seeing the same error on Google Cloud Run:
> 
> ```
> Error: Cannot find module '/usr/src/app/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-x64-glibc-120.node'
> ```
> 
> I am using this template https://github.com/GoogleCloudPlatform/cloud-run-microservice-template-nodejs

I am seeing this on MacOS M2 Max as well.

**Comment by JonasBa** [comment]
@jamespsterling @theobouwman It seems like this is attempting to load the binaries for Node version 21. We do not officially support non LTS node versions and we do not provide precompiled binaries for these environments - v21 is not LTS. You will have to compile the binaries yourself and install the required tooling (which depends on the images you are using, but tipically involves python, git and a couple other build tools). The alternative is to downgrade to v20 or wait for when v22 reaches LTS and we provide precompiled binaries.

**Comment by dancrumb** [comment]
In case this helps others: I was seeing this issue on a fresh Ubuntu box.

I'd install node via `nvm`.

Once I installed `node-gyp` via `apt`, everything worked correctly for me. Installing that brought in a _lot_ of dependencies, so I couldn't say for sure whether it was `node-gyp` or a dependency that solved the issue.

**Comment by pppdns** [comment]
> @jamespsterling @theobouwman It seems like this is attempting to load the binaries for Node version 21. We do not officially support non LTS node versions and we do not provide precompiled binaries for these environments - v21 is not LTS. You will have to compile the binaries yourself and install the required tooling (which depends on the images you are using, but tipically involves python, git and a couple other build tools). The alternative is to downgrade to v20 or wait for when v22 reaches LTS and we provide precompiled binaries.

🎉🎉🎉 **Switching to Node v20 from v21 fixed the issue for me!** 🎉🎉🎉

`package.json`:
```
  "engines": {
    "node": "20"
  },
```

I'm using `ubuntu-22` on DigitalOcean (default DO image) and `npm`.

**Comment by pppdns** [comment]
I got Node 22 to work (even though it's not yet LTS...) by updating these Sentry packages to their latest versions in `package.json`.

```
      "@sentry/cli": "^2.32.0",
      "@sentry/node": "^8.15.0",
      "@sentry/profiling-node": "^8.15.0",
...
  "engines": {
    "node": "22"
  },
```

I did this because Node 20 suddenly started throwing errors during build and deployment in the Sentry step.

> We do not officially support non LTS node versions and we do not provide precompiled binaries for these environments

It looks like these **Sentry binary versions are highly unreliable**. It would be nice to have a more robust and reliable automatic build process at Sentry to build these binaries for all Node versions (not just LTS).

My LTS Node 20 suddenly started throwing errors during build, but the non-LTS Node 22 works, which is not supposed to work based on the above comment that I quoted

**Comment by JonasBa** [comment]
@pppdns It has been a while since that comment and we actually build binaries for v22 since a few months now, so the binaries working for v22 is expected.

> I did this because Node 20 suddenly started throwing errors during build and deployment in the Sentry step.

Would you mind sharing what sort of errors you were seeing? Did you upgrade or change anything in your environment? Our code here hadnt changed, so I suspect there might be something external that caused this. Please send us the error so we can investigate

Regarding the binaries being unreliable, I would disagree that it's the actual binaries that are unreliable. That said, there is a lot of confusion and required knowledge around how nodejs and bundling works with native binaries which can unfortunately lead to errors in the setup. We'll try see if we can improve that.

**Comment by pppdns** [comment]
I'll see if I can get the error logs, if yes, I will post them.

Regarding the confusion around how these binaries are supposed to work, some extra documentation would be nice. I don't think it's available for the public currently

**Comment by JefferyHus** [comment]
Not sure why this started happening just today, the project was running fine and is in production but just trying to run it today in my local it gave me the same error:

```
npm error   code: 'MODULE_NOT_FOUND',
npm error   requireStack: [
npm error     '/Users/path/to/node_modules/@sentry/profiling-node/scripts/check-build.js'
npm error   ]
npm error }
npm error
npm error Node.js v20.15.1
```

**Comment by codeyourwayup** [comment]
> The issue is here `https://github.com/getsentry/profiling-node/blob/main/src/cpu_profiler.ts#L2`, the `versions` variable returned by the import is `20.4`, while my code is running on node 18.16.

There is an issue because the code checks your current Node.js version and retrieves the abi for version "21.0.0" (which is 120). Therefore, if I use Node.js version 18.18.0, it will use the correct profiling version. It worked!

**Comment by JonasBa** [comment]
> > The issue is here `https://github.com/getsentry/profiling-node/blob/main/src/cpu_profiler.ts#L2`, the `versions` variable returned by the import is `20.4`, while my code is running on node 18.16.
> 
> There is an issue because the code checks your current Node.js version and retrieves the abi for version "21.0.0" (which is 120). Therefore, if I use Node.js version 18.18.0, it will use the correct profiling version. It worked!

Yes, that is because we only support even major versions of nodejs as they have long term support as opposed to becoming unsupported after ~6 months. 

> Major Node.js versions enter Current release status for six months, which gives library authors time to add support for them. **After six months, odd-numbered releases (9, 11, etc.) become unsupported, and even-numbered releases (10, 12, etc.) move to Active LTS status and are ready for general use**. LTS release status is "long-term support", which typically guarantees that critical bugs will be fixed for a total of 30 months. Production applications should only use Active LTS or Maintenance LTS releases.

Source: https://nodejs.org/en/about/previous-releases
