### ISSUE TITLE
`MODULE_NOT_FOUND` when building on Windows 10

### ISSUE THREAD

**Issue by jhdcruz** [getsentry/profiling-node#211]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### SDK Version

1.2.6

### What environment is your node script running in?

- Personal Computer

### Are you using an alpine based docker image?

- [ ] Yes (please specify the version)
- [X] No (please describe your environment)

### Does the failure occur on a remote environment only?

- [ ] Yes (please describe your environment)
- [X] No (please describe your local environment)

### If you are using alpine, have you tried using latest version of alpine or (currently alpine3.16 or alpine3.17)?

- [ ] Yes (please specify the version)"
- [X] No, and I cannot upgrade

### Have you tried using the latest minor version of node (currently 16.20 or 18.15)?

- [ ] Yes (please specify the version)
- [X] No, and I cannot upgrade

### If you run npm install --verbose --foreground-scripts @sentry/profiling-node in an empty directory, what is the output?

I use `pnpm` as package manager, I don't know the script's equivalent, so I just ran the exact script using npm.

```bash
$ npm i --verbose --foreground-scripts @sentry/profiling-node
npm verb cli C:\Users\Admin\AppData\Local\fnm_multishells\10988_1700479953927\node.exe C:\Users\Admin\AppData\Local\fnm_multishells\10988_1700479953927\node_m
odules\npm\bin\npm-cli.js
npm info using npm@10.2.0
npm info using node@v21.0.0
npm verb title npm i @sentry/profiling-node
npm verb argv "i" "--loglevel" "verbose" "--foreground-scripts" "@sentry/profiling-node"
npm verb logfile logs-max:10 dir:C:\Users\Admin\AppData\Local\npm-cache\_logs\2023-11-20T11_33_19_954Z-
npm verb logfile C:\Users\Admin\AppData\Local\npm-cache\_logs\2023-11-20T11_33_19_954Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/@sentry%2fprofiling-node 2768ms (cache miss)
npm verb stack Error: Unsupported URL Type "workspace:": workspace:*
npm verb stack     at unsupportedURLType (C:\Users\Admin\AppData\Roaming\fnm\node-versions\v21.0.0\installation\node_modules\npm\node_modules\npm-package-arg\
lib\npa.js:310:15)
npm verb stack     at fromURL (C:\Users\Admin\AppData\Roaming\fnm\node-versions\v21.0.0\installation\node_modules\npm\node_modules\npm-package-arg\lib\npa.js:
367:13)
npm verb stack     at Function.resolve (C:\Users\Admin\AppData\Roaming\fnm\node-versions\v21.0.0\installation\node_modules\npm\node_modules\npm-package-arg\li
b\npa.js:83:12)
npm verb stack     at #nodeFromEdge (C:\Users\Admin\AppData\Roaming\fnm\node-versions\v21.0.0\installation\node_modules\npm\node_modules\@npmcli\arborist\lib\
arborist\build-ideal-tree.js:1048:22)
npm verb stack     at #buildDepStep (C:\Users\Admin\AppData\Roaming\fnm\node-versions\v21.0.0\installation\node_modules\npm\node_modules\@npmcli\arborist\lib\
arborist\build-ideal-tree.js:917:35)
npm verb stack     at async Arborist.buildIdealTree (C:\Users\Admin\AppData\Roaming\fnm\node-versions\v21.0.0\installation\node_modules\npm\node_modules\@npmc
li\arborist\lib\arborist\build-ideal-tree.js:196:7)
npm verb stack     at async Promise.all (index 1)
npm verb stack     at async Arborist.reify (C:\Users\Admin\AppData\Roaming\fnm\node-versions\v21.0.0\installation\node_modules\npm\node_modules\@npmcli\arbori
st\lib\arborist\reify.js:159:5)
npm verb stack     at async Install.exec (C:\Users\Admin\AppData\Roaming\fnm\node-versions\v21.0.0\installation\node_modules\npm\lib\commands\install.js:152:5
)
npm verb stack     at async module.exports (C:\Users\Admin\AppData\Roaming\fnm\node-versions\v21.0.0\installation\node_modules\npm\lib\cli-entry.js:61:5)     
npm verb cwd D:\Code\mancave-oms
npm verb Windows_NT 10.0.19045
npm verb node v21.0.0
npm verb npm  v10.2.0
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
npm verb exit 1
npm verb unfinished npm timer reify 1700480001628
npm verb unfinished npm timer reify:loadTrees 1700480001657
npm verb unfinished npm timer idealTree:buildDeps 1700480006259
npm verb unfinished npm timer idealTree:#root 1700480006262
npm verb code 1

npm ERR! A complete log of this run can be found in: C:\Users\Admin\AppData\Local\npm-cache\_logs\2023-11-20T11_33_19_954Z-debug-0.log

```

### Crash report

pnpm build / turbo build result:

```log
{{project}}:build: cache miss, executing c6c20dc3ab5c90c6
{{project}}:build: 
{{project}}:build: > {{project}}@ build D:\Code\{{project_dir}}\apps\admin
{{project}}:build: > next build
{{project}}:build: 
{{project}}:build:    ▲ Next.js 14.0.2
{{project}}:build:    - Environments: .env.local
{{project}}:build: 
{{project}}:build:    Creating an optimized production build ...
{{project}}:build: (node:11176) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
{{project}}:build: (Use `node --trace-deprecation ...` to show where the warning was created)
{{project}}:build:  ✓ Compiled successfully
{{project}}:build:    Linting and checking validity of types ...
{{project}}:build:    Collecting page data ...
{{project}}:build: Error: Cannot find module 'D:\Code\{{project_dir}}\node_modules\.pnpm\@sentry+profiling-node@1.2.6\node_modules\@sentry\profiling-node\lib\sen
try_cpu_profiler-win32-x64-120.node'
{{project}}:build: Require stack:
{{project}}:build: - D:\Code\{{project_dir}}\node_modules\.pnpm\@sentry+profiling-node@1.2.6\node_modules\@sentry\profiling-node\lib\index.js
{{project}}:build: - D:\Code\{{project_dir}}\apps\admin\.next\server\app\(login)\auth\route.js
{{project}}:build: - D:\Code\{{project_dir}}\node_modules\.pnpm\next@14.0.2_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\require.js
{{project}}:build: - D:\Code\{{project_dir}}\node_modules\.pnpm\next@14.0.2_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\load-components.js
{{project}}:build: - D:\Code\{{project_dir}}\node_modules\.pnpm\next@14.0.2_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\utils.js
{{project}}:build: - D:\Code\{{project_dir}}\node_modules\.pnpm\next@14.0.2_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\worker.js
{{project}}:build: - D:\Code\{{project_dir}}\node_modules\.pnpm\next@14.0.2_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\jest-worker\processChil
d.js
{{project}}:build:     at Module._resolveFilename (node:internal/modules/cjs/loader:1138:15)
{{project}}:build:     at D:\Code\{{project_dir}}\node_modules\.pnpm\next@14.0.2_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\require-hook.js:54:3
6
{{project}}:build:     at Module._load (node:internal/modules/cjs/loader:979:27)
{{project}}:build:     at Module.require (node:internal/modules/cjs/loader:1229:19)
{{project}}:build:     at mod.require (D:\Code\{{project_dir}}\node_modules\.pnpm\next@14.0.2_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\require
-hook.js:64:28)
{{project}}:build:     at require (node:internal/modules/helpers:177:18)
{{project}}:build:     at importCppBindingsModule (D:\Code\{{project_dir}}\node_modules\.pnpm\@sentry+profiling-node@1.2.6\node_modules\@sentry\profiling-node\li
b\index.js:18458:10)
{{project}}:build:     at Object.<anonymous> (D:\Code\{{project_dir}}\node_modules\.pnpm\@sentry+profiling-node@1.2.6\node_modules\@sentry\profiling-node\lib\ind
ex.js:18460:34)
{{project}}:build:     at Module._compile (node:internal/modules/cjs/loader:1369:14)
{{project}}:build:     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10) {
{{project}}:build:   code: 'MODULE_NOT_FOUND',
{{project}}:build:   requireStack: [
{{project}}:build:     'D:\\Code\\{{project_dir}}\\node_modules\\.pnpm\\@sentry+profiling-node@1.2.6\\node_modules\\@sentry\\profiling-node\\lib\\index.js',     
{{project}}:build:     'D:\\Code\\{{project_dir}}\\apps\\admin\\.next\\server\\app\\(login)\\auth\\route.js',
{{project}}:build:     'D:\\Code\\{{project_dir}}\\node_modules\\.pnpm\\next@14.0.2_react-dom@18.2.0_react@18.2.0\\node_modules\\next\\dist\\server\\require.js',
{{project}}:build:     'D:\\Code\\{{project_dir}}\\node_modules\\.pnpm\\next@14.0.2_react-dom@18.2.0_react@18.2.0\\node_modules\\next\\dist\\server\\load-compone
nts.js',
{{project}}:build:     'D:\\Code\\{{project_dir}}\\node_modules\\.pnpm\\next@14.0.2_react-dom@18.2.0_react@18.2.0\\node_modules\\next\\dist\\build\\utils.js',   
{{project}}:build:     'D:\\Code\\{{project_dir}}\\node_modules\\.pnpm\\next@14.0.2_react-dom@18.2.0_react@18.2.0\\node_modules\\next\\dist\\build\\worker.js',  
{{project}}:build:     'D:\\Code\\{{project_dir}}\\node_modules\\.pnpm\\next@14.0.2_react-dom@18.2.0_react@18.2.0\\node_modules\\next\\dist\\compiled\\jest-worke
r\\processChild.js'
{{project}}:build:   ]
{{project}}:build: }
{{project}}:build: 
{{project}}:build: > Build error occurred
{{project}}:build: Error: Failed to collect page data for /auth
{{project}}:build:     at D:\Code\{{project_dir}}\node_modules\.pnpm\next@14.0.2_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\utils.js:1217:15     
{{project}}:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
{{project}}:build:   type: 'Error'
{{project}}:build: }
{{project}}:build:  ELIFECYCLE  Command failed with exit code 1.
{{project}}:build: ERROR: command finished with error: command (D:\Code\{{project_dir}}\apps\admin) pnpm run build exited (1)
{{project}}#build: command (D:\Code\{{project_dir}}\apps\admin) pnpm run build exited (1)
```

Running builds in Linux works fine, as well as vercel and CI builds.

**Comment by jhdcruz** [comment]
Find out the cause.

Apparently it **does not build properly when running builds in `Git Bash`.**
cmd and powershell builds just fine.
