### ISSUE TITLE
`__dirname is not defined in ES module scope` error when setting up profiling for Remix

### ISSUE THREAD

**Issue by jackie-greenbaum** [getsentry/profiling-node#217]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### SDK Version

7.81.1

### Link to Sentry event

N/A

### What environment is your node script running in?

Remix 2.1.0

### How is your code deployed and bundled?

Remix

### Steps to Reproduce

Followed the steps to set up my Remix application with profiling as described by the sidebar that appears when clicking `Set up Profiling`

<img width="967" alt="Screenshot 2023-12-06 at 2 30 20 PM" src="https://github.com/getsentry/profiling-node/assets/23202225/96318fb7-0d59-419b-83f0-b2396f00b657">

Below is my code for setting up `@sentry/remix`  in my `entry.server.ts` file.

```
 import * as SentryRemix from "@sentry/remix"

 SentryRemix.init({
   dsn: "omitted",
   tracesSampleRate: 1,
   profilesSampleRate: 1,
   integrations: [
     new SentryRemix.Integrations.LocalVariables({
       captureAllExceptions: true,
     }),
     new ProfilingIntegration()
   ],
 })
```

### Expected Result

Profiling works correctly

### Actual Result

 When I deploy this, I see the following 500 error

```
2023-12-06T19:44:49.312Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "ReferenceError",
    "errorMessage": "__dirname is not defined in ES module scope",
    "stack": [
        "ReferenceError: __dirname is not defined in ES module scope",
        "    at node_modules/@sentry/profiling-node/lib/index.js (file:///var/task/ui/build/index.mjs:48006:777)",
        "    at file:///var/task/ui/build/index.mjs:26:50",
        "    at file:///var/task/ui/build/index.mjs:108280:37"
    ]
}
```

**Comment by anonrig** [comment]
Which Node.js version do you use in your AWS Lambda?

**Comment by jackie-greenbaum** [comment]
> Which Node.js version do you use in your AWS Lambda?

18.12.0

> @jackie-greenbaum could you provide us with a small reproducible example by any chance?

So, I was able to create a new remix app with sentry from scratch and configure profiling. My current guess is that this issue something to do with my AWS configuration

**Comment by brettdh** [comment]
HI, I work with @jackie-greenbaum . Marking `@sentry/profiling-node` as external isn't going to work for us, as we're intentionally bundling everything to avoid deploying `node_modules` to Lambda, which has a limited total deployment package size.

I do vaguely recall other issues with node builtins that needed to be polyfilled but I haven't been able to track down the issues/discussions I was looking at. It may have been back when we were trying to bundle this as CommonJS, or maybe I'm misremembering things.

@jackie-greenbaum Were you testing the minimal repro app with `remix dev`? I wonder what happens if we run `remix build` with [`"serverDependenciesToBundle": "all"`](https://remix.run/docs/en/main/file-conventions/remix-config#serverdependenciestobundle), and run it with [`remix serve`](https://remix.run/docs/en/main/other-api/serve), which would be closer to our setup (minus the AWS part).

**Comment by jackie-greenbaum** [comment]
[Here's](https://github.com/jackie-greenbaum/remix-sentry-example) a small sample project exhibiting the issue in case it would be at all helpful

As @brettdh mentioned, we are unable to treat `@sentry/profiling` as external due to Lambda package size limits
